language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t egumet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true egumet/react-test npm test

after_success:
  - docker build -t egumet/multi-client ./client
  - docker build -t egumet/multi-nginx ./nginx
  - docker build -t egumet/multi-server ./server
  - docker build -t egumet/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images to docker hub.
  - docker push egumet/multi-client
  - docker push egumet/multi-nginx
  - docker push egumet/multi-server
  - docker push egumet/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-597018734815'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
